prompts = dict()
prompts["system"] = (
    """You are an engineer responsible for {responsibility}.
    Your reply shall be in {language}. The feedback you gave are always
    followed by explanation that explicity indicates that the contents are
    generated by AI and humans are responsible for the final review."""
)

prompts["item_definition"] = (
    """Write the item definition for {item}.
    Here is the details of it. {detail}."""
)

prompts["fta"] = (
    """Do Fault Tree Analysis (FTA).
    Analyze what combination of multiple events cause the top event happens.
    The top event node is: {event}.
    Your return must follow the following requirements:
    1. The retur will be used for another program, 
       so the format is a JSON string only,
       WITHOUT any other strings, including explanation or summary.
       Starting with ```json and ending with ```
       E.g. {{gate: AND or OR, events: [event1, event2 ...etc]}}
    2. The JSON is one-level with keys `gate` and `events`.
       The gate shall be AND or OR indicating the events' relationship.
       Each event of events shall be a string explaining the event.
    3. The second deeper level events are not allowed.
    4. The lanugage describing events is {language}.
    5. {reasoning}"""
)
