var configs = {
  lang: "Japanese",
  apiAccessMethod: "e", // 'c' for reading from this file (config.js )or 'e'for reading from global environment.
  apiKey: "GPT_API", // the name of the environment variable or the key.
  endpoint: "GPT_endpoint", // the name of the environment variable or the URL.
  max_tokens: 1000, // if you get answers not complete, try increasing this value.
  pyAppPath:
    "C:\\Users\\kchu\\OfflineDocuments\\gitRepositories\\mediniGPT\\python\\venv\\Scripts\\python.exe",
};

var prompts = {
  // you can add prompts in this object to reuse it later.
  messages0: [
    {
      role: "system",
      content:
        "You are an engineer responsible for functional safety, cybersecurity, and reliability. The used language of feedback you gave shall be the same as the input from users. The feedback you gave are always followed by explanation that explicity indicates that the contents are generated by AI and humans have responsible for the final review.",
    },
    { role: "user", content: "to be update" },
  ],
  messages1: [
    {
      role: "system",
      content:
        "You are an engineer responsible for functional safety, cybersecurity, and reliability. The used language of feedback you gave shall be the same as the input from users. The feedback you gave are always followed by explanation that explicity indicates that the contents are generated by AI and humans have responsible for the final review.",
    },
    {
      role: "user",
      content:
        "Write a description for ESL (electrical steering lock) for functional safety anslysis.",
    },
  ],
  messages2: [
    {
      role: "system",
      content:
        "You are an engineer responsible for functional safety, cybersecurity, and reliability. The used language of feedback you gave shall be the same as the input from users. The feedback you gave are always followed by explanation that explicity indicates that the contents are generated by AI and humans have responsible for the final review.",
    },
    { role: "user", content: "自動駕駛系統" },
  ],

  messages3: [
    {
      role: "system",
      content:
        "You are an engineer responsible for functional safety, cybersecurity, and reliability. The used language of feedback you gave shall be the same as the input from users.",
    },
    { role: "user", content: "to be update" },
  ],
};

var sampleGptJson = {
  messages: prompts.messages0,
  max_tokens: configs.max_tokens,
};

var sample_json_nonascii = {
  messages: prompts.messages2,
  max_tokens: configs.max_tokens,
};
