//$EXPERIMENTAL$
load('../.lib/AI/utils.js');
load("../.lib/helper.js");
load("../.lib/AI/configs.js");
load("../.lib/ui.js");

var reader = {
    getName: function(obj){return obj.name;},
    getDesc: function(obj){return obj.description;} 
};

var writer = {
    decideWriteMode: function(){
        var mode = prompt('Type "a" for append mode, or "r" for replace mode.','a');
        return mode;
    },
    replaceOldDesc: function(selObj, newContent){
        // use pointer to manipulate external objects
        selObj.description = newContent;
        return;
    },
    appendOldDesc: function(selObj, newContent){
        // use pointer to manipulate external objects
        selObj.description = selObj.description + '\n' + newContent;
        return;
    },
    updateDesc: function(selObj, content, mode){
        while(mode != 'a' && mode != 'r') {mode = this.decideWriteMode();}
        if (mode == 'a'){this.appendOldDesc(selObj, content);}        
        if (mode == 'r'){this.replaceOldDesc(selObj, content);}
        return;
    },
    addDisclaimer: function(content){
        var header  = '<AI generated>\n';
        var time    = 'Contents are appended at ' + utils.getCurrentTime() + '\n';
        var warning = '!!!YOU ARE REQUIRED TO REVIEW THE RESULTS GENERATED BY AI!!!\n';
        var footer  = '</AI generated>\n';
        return header + time + warning + content + '\n' + footer;
    }
};

function main(){
    var name = reader.getName(selection[0]);
    var desc = reader.getDesc(selection[0]);
    var promptContent = 'Write a description for the ' + name + '. Here are some useful information. ' + desc + ' Put the information together and ensure that the aritcle you write is comprehensive but easy to understand.';
    var gptJson = utils.gptJsonGenerator(prompts['messages0'], 1, promptContent, sampleGptJson);
    var gpt = new GptConversation(gptJson);
    var content = writer.addDisclaimer(gpt.getContent());
    writer.updateDesc(selection[0], content, 'a');
    return;
}

main();